###############
## 
####
GPU: [2]
# GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  #SESSION: 'MPRNet'
  SESSION: 'DAWN'
# Optimization arguments.
OPTIM:
  BATCH_SIZE: 10
  #BATCH_SIZE: 16
  NUM_EPOCHS: 1000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 5e-4
  LR_MIN: 1e-7
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: True
  # RESUME: False
  #TRAIN_PS: 256
  TRAIN_PS: 192
  #VAL_PS: 128
  VAL_PS: 96
  TRAIN_DIR: './Datasets/train'       # path to training data
  VAL_DIR: './Datasets/test/Rain100L' # path to validation data
  #TRAIN_DIR: './Datasets/lowlight/train'       # path to training data
  #VAL_DIR: './Datasets/lowlight/test/LOL1000' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
